# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ecc9c72de5967748ec92dd0767dda2274af46b6131f068bf1841e384b637fca45f873618471d5c6071a5a1308229d1e099459e54b5f02ac19b50857e6d7676

test:
  secret_key_base: 5a89498f113d642df1fc02a451c8b1df6d8576926031e48a0ecaea9f2adbe18326219c5d8fc21d28aca9f47d187a30fa87c4ab7f72c315913c0da7a8d643e96b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 580a99dd8d2b4ec2db00714ff998a89c89dc5de7bdb7389a6d25bc68c5ff664b76e85d2226da01916927b05697dc049e58a4eae6c3f8ce6a0f70f667d8d842df
